"""Shared fixtures for the integration/data-quality test suites.

These tests exercise `ingestion/common/base_ingest.py` against real files
generated by `scripts/generate_synthetic_data.py` (either `data/sample/` or a
fuller `data/generated/` run), but fake out the metadata database with a
simple in-memory dict-backed stand-in instead of requiring a live Postgres
connection for every test. This is the exact pattern used to manually verify
the ingestion engine during Phase 4 development (see docs/checklist.md) --
lifted here into a reusable pytest fixture per docs/remaining_work.md's
Phase 8 priority list item #8.

Row-level/warehouse-level tests (dbt dedup, invalid-mapping handling) instead
talk to a real Postgres database, because that behavior is implemented in SQL
(dbt models), not Python -- there is nothing to fake there. Those tests read
connection info from the same WAREHOUSE_DB_*/METADATA_DB_* environment
variables the application code uses (see .env.example) and are skipped with a
clear reason if no database is reachable, rather than failing confusingly.
"""

from __future__ import annotations

import shutil
import sys
import uuid
from contextlib import contextmanager
from pathlib import Path
from unittest import mock

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

SAMPLE_DIR = REPO_ROOT / "data" / "sample"
GENERATED_DIR = REPO_ROOT / "data" / "generated"
LAKE_DIR = REPO_ROOT / "data" / "lake"
SCHEMA_STATE_DIR = REPO_ROOT / "data" / "_schema_state"


@pytest.fixture
def clean_lake_state():
    """Ensures each test starts from a clean local lake + schema-state cache,
    and cleans up afterward so tests don't leak state into each other or into
    a real (non-test) run of the pipeline.
    """
    shutil.rmtree(LAKE_DIR, ignore_errors=True)
    shutil.rmtree(SCHEMA_STATE_DIR, ignore_errors=True)
    yield
    shutil.rmtree(LAKE_DIR, ignore_errors=True)
    shutil.rmtree(SCHEMA_STATE_DIR, ignore_errors=True)


class FakeMetadataDB:
    """In-memory stand-in for ingestion/common/db.py, backed by plain dicts
    instead of a live Postgres connection. Mirrors the real module's function
    signatures closely enough that `ingestion.common.base_ingest.run_ingestion`
    can't tell the difference.
    """

    def __init__(self):
        self.watermarks: dict[tuple[str, str], object] = {}
        self.runs: dict[uuid.UUID, dict] = {}
        self.schema_changes: list[tuple] = []

    @contextmanager
    def connection_scope(self):
        class _FakeConn:
            def cursor(_self):
                return mock.MagicMock()

            def commit(_self):
                pass

            def close(_self):
                pass

        yield _FakeConn()

    def get_watermark(self, conn, source_name, environment="local"):
        return self.watermarks.get((source_name, environment))

    def set_watermark(self, conn, source_name, business_date, environment="local"):
        self.watermarks[(source_name, environment)] = business_date

    def start_run(self, conn, dag_id, task_id, source_name, run_type, business_date=None):
        run_id = uuid.uuid4()
        self.runs[run_id] = {"status": "RUNNING", "dag_id": dag_id, "source_name": source_name}
        return run_id

    def finish_run(self, conn, run_id, status, **kwargs):
        self.runs[run_id] = {**self.runs.get(run_id, {}), "status": status, **kwargs}

    def log_schema_change(self, conn, source_name, change_type, is_breaking, **kwargs):
        self.schema_changes.append((source_name, change_type, is_breaking, kwargs))

    def log_quarantine(self, conn, run_id, source_name, business_date, rejection_reason, record_count, quarantine_file_path):
        pass

    def log_dq_result(self, *args, **kwargs):
        pass


@pytest.fixture
def fake_db(monkeypatch):
    """Patches ingestion.common.db's module-level functions to route through
    a fresh FakeMetadataDB instance for the duration of one test, and returns
    that instance so the test can assert on its state (watermarks advanced,
    schema changes logged, etc.).
    """
    from ingestion.common import db

    fake = FakeMetadataDB()
    monkeypatch.setattr(db, "connection_scope", fake.connection_scope)
    monkeypatch.setattr(db, "get_watermark", fake.get_watermark)
    monkeypatch.setattr(db, "set_watermark", fake.set_watermark)
    monkeypatch.setattr(db, "start_run", fake.start_run)
    monkeypatch.setattr(db, "finish_run", fake.finish_run)
    monkeypatch.setattr(db, "log_schema_change", fake.log_schema_change)
    monkeypatch.setattr(db, "log_quarantine", fake.log_quarantine)
    monkeypatch.setattr(db, "log_dq_result", fake.log_dq_result)
    return fake


def require_sample_data():
    if not SAMPLE_DIR.exists():
        pytest.skip(f"{SAMPLE_DIR} does not exist -- run scripts/generate_synthetic_data.py first")


def require_generated_data():
    if not GENERATED_DIR.exists():
        pytest.skip(
            f"{GENERATED_DIR} does not exist -- run scripts/generate_synthetic_data.py "
            "(full run, no --output-dir override) to exercise the schema-change scenario, "
            "which only occurs after dbt_project's schema_change_date (2025-09-01) and needs "
            "the full 18-month default date range to be reached"
        )


@pytest.fixture
def warehouse_engine():
    """Real SQLAlchemy engine against WAREHOUSE_DB_* env vars. Skips (not
    fails) if the database isn't reachable, since these tests validate SQL
    behavior (dbt-built dedup/mapping logic) that has no in-memory
    equivalent to fall back to.
    """
    import os

    from sqlalchemy import create_engine, text

    host = os.environ.get("WAREHOUSE_DB_HOST", "localhost")
    port = os.environ.get("WAREHOUSE_DB_PORT", "5432")
    name = os.environ.get("WAREHOUSE_DB_NAME", "cpg_pulse_warehouse")
    user = os.environ.get("WAREHOUSE_DB_USER", "cpgpulse")
    password = os.environ.get("WAREHOUSE_DB_PASSWORD", "")
    engine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{name}")
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except Exception as exc:
        pytest.skip(f"warehouse database not reachable ({exc}) -- start it (e.g. `make up`) to run this test")
    return engine
