"""Integration tests for the ingestion engine (ingestion/common/base_ingest.py),
against real data generated by scripts/generate_synthetic_data.py.

These exercise the exact scenarios manually verified during Phase 4
development (see docs/checklist.md): idempotent re-ingestion, schema-drift
detection against the real reserved_qty -> reserved_units rename, and raw
landing continuing even when a breaking schema change is detected (raw is a
byte-exact copy -- see docs/remaining_work.md architectural decision #5).

Run: pytest tests/integration/test_ingestion.py -v
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path


from ingestion.common import base_ingest
from tests.conftest import GENERATED_DIR, LAKE_DIR, SAMPLE_DIR, require_generated_data, require_sample_data


def _inventory_config(generated_dir: Path) -> base_ingest.SourceConfig:
    return base_ingest.SourceConfig(
        source_name="retail_inventory",
        generated_dir=str(generated_dir / "retail_inventory"),
        required_columns=[
            "retailer_id", "store_id", "retailer_product_id", "snapshot_date",
            "on_hand_units", "on_order_units", "available_units",
        ],
        partitioned=True,
        preferred_format="csv",
    )


def _pos_sales_config(generated_dir: Path) -> base_ingest.SourceConfig:
    return base_ingest.SourceConfig(
        source_name="retail_pos_sales",
        generated_dir=str(generated_dir / "retail_pos_sales"),
        required_columns=[
            "retailer_id", "store_id", "retailer_product_id", "transaction_date",
            "units_sold", "gross_sales", "discount_amount", "net_sales",
            "regular_price", "selling_price", "sales_channel",
        ],
        partitioned=True,
        preferred_format="csv",
    )


class TestIdempotency:
    def test_second_run_is_skipped(self, fake_db, clean_lake_state):
        require_sample_data()
        cfg = _inventory_config(SAMPLE_DIR)

        first = base_ingest.run_ingestion(cfg)
        assert first.status == "SUCCEEDED"
        assert first.files_landed > 0

        second = base_ingest.run_ingestion(cfg)
        assert second.status == "SKIPPED"
        assert second.files_landed == 0
        assert second.records_read == 0

    def test_watermark_advances_to_max_extract_date(self, fake_db, clean_lake_state):
        require_sample_data()
        cfg = _inventory_config(SAMPLE_DIR)
        base_ingest.run_ingestion(cfg)

        watermark = fake_db.get_watermark(None, "retail_inventory", "local")
        assert watermark is not None
        assert isinstance(watermark, dt.date)

    def test_rerun_does_not_duplicate_landed_files(self, fake_db, clean_lake_state):
        """Re-running ingestion for the same data must not double the number
        of files landed in the raw lake -- the core idempotency guarantee."""
        require_sample_data()
        cfg = _inventory_config(SAMPLE_DIR)
        base_ingest.run_ingestion(cfg)

        landed_after_first = list((LAKE_DIR / "raw" / "retail_inventory").rglob("*.csv"))
        base_ingest.run_ingestion(cfg)  # should be a no-op (SKIPPED)
        landed_after_second = list((LAKE_DIR / "raw" / "retail_inventory").rglob("*.csv"))

        assert len(landed_after_first) == len(landed_after_second)
        assert len(landed_after_first) > 0


class TestLateArrivingData:
    def test_backfill_range_discovers_files_regardless_of_watermark(self, fake_db, clean_lake_state):
        """A late-arriving file's extract_date can be earlier than the
        current watermark (it arrived late, but the business/extract dates
        it carries are old). The backfill code path must still be able to
        pick such files up on demand -- this is exactly how a late-arriving
        partition gets reprocessed (docs/architecture.md section 10)."""
        require_sample_data()
        cfg = _inventory_config(SAMPLE_DIR)

        # Simulate "we've already ingested through today" by running once
        # normally first (watermark advances to the max extract_date seen).
        first = base_ingest.run_ingestion(cfg)
        assert first.status == "SUCCEEDED"
        watermark_after_first = fake_db.get_watermark(None, "retail_inventory", "local")

        # A late file for an *early* extract_date arrives. Because backfill_range
        # is explicit, it must be discovered even though it's "before" the
        # watermark -- normal (non-backfill) discovery would skip it.
        early_range = (dt.date(2025, 1, 1), dt.date(2025, 1, 5))
        result = base_ingest.run_ingestion(cfg, backfill_range=early_range)

        assert result.status in ("SUCCEEDED", "SKIPPED")
        if result.status == "SUCCEEDED":
            assert result.batches_landed > 0
        # Watermark bookkeeping is untouched by backfills that target dates
        # already covered by normal (non-backfill) runs.
        assert fake_db.get_watermark(None, "retail_inventory", "local") == watermark_after_first


class TestSchemaChangeDetection:
    def test_reserved_qty_to_reserved_units_rename_detected(self, fake_db, clean_lake_state):
        """The generator (scripts/data_gen/quality_issues.py) renames this
        column from reserved_qty to reserved_units at dbt_project's
        schema_change_date (2025-09-01). Only occurs in a full-range
        generation (default --end-date reaches past that date) -- data/sample
        alone (2025-01-01..02-28) never crosses the boundary."""
        require_generated_data()
        cfg = _inventory_config(GENERATED_DIR)

        result = base_ingest.run_ingestion(cfg)
        assert result.status == "SUCCEEDED"

        change_types = {(c[0], c[1]) for c in fake_db.schema_changes}
        assert ("retail_inventory", "COLUMN_ADDED") in change_types or ("retail_inventory", "TYPE_CHANGED") in change_types
        # reserved_units appears where it didn't before -> COLUMN_ADDED (or,
        # depending on which batch is read first, the reverse direction
        # COLUMN_REMOVED for reserved_qty). Either is evidence the rename was
        # detected, not silently ignored.
        column_names_touched = {c[3].get("column_name") for c in fake_db.schema_changes if c[3].get("column_name")}
        assert "reserved_units" in column_names_touched or "reserved_qty" in column_names_touched

    def test_breaking_schema_change_does_not_block_raw_landing(self, fake_db, clean_lake_state):
        """Architectural decision (docs/remaining_work.md #5): raw landing
        must succeed even when a breaking schema change is detected -- only
        standardization is allowed to reject/quarantine. This is what lets
        the raw layer stay a true byte-exact copy of every source file."""
        require_generated_data()
        cfg = _inventory_config(GENERATED_DIR)

        result = base_ingest.run_ingestion(cfg)
        assert result.status == "SUCCEEDED"
        assert result.files_landed > 0
        # Batches landed should equal the number of extract_date partitions
        # discovered -- none skipped due to the schema change.
        assert result.batches_landed > 0


class TestRawLayerIsByteExactCopy:
    def test_landed_file_content_matches_source_file_content(self, fake_db, clean_lake_state):
        require_sample_data()
        cfg = _inventory_config(SAMPLE_DIR)
        base_ingest.run_ingestion(cfg)

        landed_files = sorted((LAKE_DIR / "raw" / "retail_inventory").rglob("*.csv"))
        assert landed_files, "expected at least one landed file"

        source_files = sorted((SAMPLE_DIR / "retail_inventory" / "csv").rglob("*.csv"))
        source_by_name = {f.name: f for f in source_files}

        checked = 0
        for landed in landed_files:
            source = source_by_name.get(landed.name)
            if source is None:
                continue
            assert landed.read_bytes() == source.read_bytes(), f"{landed.name} was mutated during landing"
            checked += 1
        assert checked > 0
